version: '3.8'

services:
  api:
    image: ghcr.io/debelistic/payment-microservice:ed492c063812810da307ae81ed3890699e1fc667
    ports:
      - "3667:3667"
    environment:
      - PORT=3667
      - NODE_ENV=production
    volumes:
      - payment-data:/app/data
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3667/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

volumes:
  payment-data:

networks:
  app-network:
