name: Deploy Payment Microservice

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
  docker-build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build --tag ghcr.io/debelistic/payment-microservice:${{ github.sha }} .
          docker push ghcr.io/debelistic/payment-microservice:${{ github.sha }}
  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.DEV_SERVER_USER }}/payment-microservice
            ls -lrt
            sudo sed -i "s|image: ghcr.io/debelistic/payment-microservice:.*|image: ghcr.io/debelistic/payment-microservice:${{ github.sha }}|g" payment-compose.yml
            sudo docker stack deploy -c payment-compose.yml --with-registry-auth payment-microservice
          
